In [4]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [6]:
data = pd.read_csv('ipl_project\datasets\deliveries.csv')

FileNotFoundError: [Errno 2] File b'ipl_project\\datasets\\deliveries.csv' does not exist: b'ipl_project\\datasets\\deliveries.csv'

In [4]:
data

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150430,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,1,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150431,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,2,SR Watson,KL Rahul,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150432,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,3,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,0,KL Rahul,bowled,NaN
150433,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,4,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150434,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,5,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150435,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,6,SR Watson,Sachin Baby,BCJ Cutting,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150436,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,1,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150437,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,2,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150438,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,SR Watson,caught,MC Henriques
150439,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,4,Sachin Baby,STR Binny,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150441,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,6,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150442,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,1,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150443,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,2,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150444,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,3,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150445,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150446,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150447,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150448,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,1,0,1,STR Binny,run out,DJ Hooda
150449,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150450,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
150451,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150452,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150454,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,1,CJ Jordan,Sachin Baby,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [5]:
data.groupby('batting_team')['total_runs'].sum().sort_values(ascending=False)

batting_team
Mumbai Indians                 24521
Royal Challengers Bangalore    23436
Kings XI Punjab                23068
Kolkata Knight Riders          21965
Delhi Daredevils               21953
Chennai Super Kings            20899
Rajasthan Royals               17703
Sunrisers Hyderabad            11652
Deccan Chargers                11463
Pune Warriors                   6358
Gujarat Lions                   4862
Rising Pune Supergiant          2470
Rising Pune Supergiants         2063
Kochi Tuskers Kerala            1901
Name: total_runs, dtype: int64

In [6]:
data['match_id'].count()

150460

In [7]:
#mean score of batsmen
data0 = data.set_index(['match_id','inning'])
data0

                                batting_team                 bowling_team  \
match_id inning
1        1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
         1               Sunrisers Hyderabad  Royal Challengers Bangalore
...                                      ...                          ...
636      2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad
         2       Royal Challengers Bangalore          Sunrisers Hyderabad

                 over  ball        batsman    non_striker             bowler  \
match_id inning
1        1          1     1      DA Warner       S Dhawan           TS Mills
         1          1     2      DA Warner       S Dhawan           TS Mills
         1          1     3      DA Warner       S Dhawan           TS Mills
         1          1     4      DA Warner       S Dhawan           TS Mills
         1          1     5      DA Warner       S Dhawan           TS Mills
         1          1     6       S Dhawan      DA Warner           TS Mills
         1          1     7       S Dhawan      DA Warner           TS Mills
         1          2     1       S Dhawan      DA Warner        A Choudhary
         1          2     2      DA Warner       S Dhawan        A Choudhary
         1          2     3      DA Warner       S Dhawan        A Choudhary
         1          2     4      DA Warner       S Dhawan        A Choudhary
         1          2     5      DA Warner       S Dhawan        A Choudhary
         1          2     6   MC Henriques       S Dhawan        A Choudhary
         1          2     7   MC Henriques       S Dhawan        A Choudhary
         1          3     1       S Dhawan   MC Henriques           TS Mills
         1          3     2   MC Henriques       S Dhawan           TS Mills
         1          3     3   MC Henriques       S Dhawan           TS Mills
         1          3     4   MC Henriques       S Dhawan           TS Mills
         1          3     5       S Dhawan   MC Henriques           TS Mills
         1          3     6   MC Henriques       S Dhawan           TS Mills
         1          4     1   MC Henriques       S Dhawan          YS Chahal
         1          4     2   MC Henriques       S Dhawan          YS Chahal
         1          4     3       S Dhawan   MC Henriques          YS Chahal
         1          4     4       S Dhawan   MC Henriques          YS Chahal
         1          4     5   MC Henriques       S Dhawan          YS Chahal
         1          4     6       S Dhawan   MC Henriques          YS Chahal
         1          5     1       S Dhawan   MC Henriques          S Aravind
         1          5     2   MC Henriques       S Dhawan          S Aravind
         1          5     3       S Dhawan   MC Henriques          S Aravind
         1          5     4   MC Henriques       S Dhawan          S Aravind
...               ...   ...            ...            ...                ...
636      2         16     1       KL Rahul      SR Watson        BCJ Cutting
         2         16     2      SR Watson       KL Rahul        BCJ Cutting
         2         16     3       KL Rahul      SR Watson        BCJ Cutting
         2         16     4    Sachin Baby      SR Watson        BCJ Cutting
         2         16     5    Sachin Baby      SR Watson        BCJ Cutting
         2         16     6      SR Watson    Sachin Baby        BCJ Cutting
         2         17     1      SR Watson    Sachin Baby  Mustafizur Rahman
         2         17     2      SR Watson    Sachin Baby  Mustafizur Rahman
         2         17     3      SR Watson    Sachin Baby  Mustafizur Rahman
         2         17     4    Sachin Baby      STR Binny  Mustafizur Rahman
         2         17     5      STR Binny    Sachin Baby  Mustafizur Rahman
         2         17     6      STR Binny    Sachin Baby  Mustafizur Rahman
         2         18     1      STR Binny    Sachin Baby            B Kumar
         2         18     2      STR Binny    Sachin Baby            B Kumar
         2         18     3    Sachin Baby      STR Binny            B Kumar
         2         18     4      STR Binny    Sachin Baby            B Kumar
         2         18     5      STR Binny    Sachin Baby            B Kumar
         2         18     6    Sachin Baby      STR Binny            B Kumar
         2         19     1      STR Binny    Sachin Baby  Mustafizur Rahman
         2         19     2      CJ Jordan    Sachin Baby  Mustafizur Rahman
         2         19     3      CJ Jordan    Sachin Baby  Mustafizur Rahman
         2         19     4      CJ Jordan    Sachin Baby  Mustafizur Rahman
         2         19     5    Sachin Baby      CJ Jordan  Mustafizur Rahman
         2         19     6    Sachin Baby      CJ Jordan  Mustafizur Rahman
         2         20     1      CJ Jordan    Sachin Baby            B Kumar
         2         20     2    Sachin Baby      CJ Jordan            B Kumar
         2         20     3    Sachin Baby      CJ Jordan            B Kumar
         2         20     4  Iqbal Abdulla    Sachin Baby            B Kumar
         2         20     5    Sachin Baby  Iqbal Abdulla            B Kumar
         2         20     6  Iqbal Abdulla    Sachin Baby            B Kumar

                 is_super_over  wide_runs  bye_runs  legbye_runs  noball_runs  \
match_id inning
1        1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          2         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            1            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            1
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
         1                   0          0         0            0            0
...                        ...        ...       ...          ...          ...
636      2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            1            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            1            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0
         2                   0          0         0            1            0
         2                   0          0         0            0            0
         2                   0          0         0            0            0

                 penalty_runs  batsman_runs  extra_runs  total_runs  \
match_id inning
1        1                  0             0           0           0
         1                  0             0           0           0
         1                  0             4           0           4
         1                  0             0           0           0
         1                  0             0           2           2
         1                  0             0           0           0
         1                  0             0           1           1
         1                  0             1           0           1
         1                  0             4           0           4
         1                  0             0           1           1
         1                  0             6           0           6
         1                  0             0           0           0
         1                  0             0           0           0
         1                  0             4           0           4
         1                  0             1           0           1
         1                  0             0           0           0
         1                  0             0           0           0
         1                  0             3           0           3
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             0           0           0
         1                  0             1           0           1
         1                  0             0           0           0
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             1           0           1
         1                  0             2           0           2
...                       ...           ...         ...         ...
636      2                  0             1           0           1
         2                  0             1           0           1
         2                  0             0           0           0
         2                  0             0           0           0
         2                  0             1           0           1
         2                  0             1           0           1
         2                  0             0           0           0
         2                  0             2           0           2
         2                  0             0           0           0
         2                  0             1           0           1
         2                  0             6           0           6
         2                  0             1           0           1
         2                  0             0           0           0
         2                  0             1           0           1
         2                  0             1           0           1
         2                  0             0           0           0
         2                  0             0           1           1
         2                  0             4           0           4
         2                  0             1           0           1
         2                  0             2           0           2
         2                  0             0           0           0
         2                  0             0           1           1
         2                  0             2           0           2
         2                  0             6           0           6
         2                  0             1           0           1
         2                  0             2           0           2
         2                  0             0           0           0
         2                  0             0           1           1
         2                  0             1           0           1
         2                  0             4           0           4

                player_dismissed dismissal_kind        fielder
match_id inning
1        1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1             DA Warner         caught  Mandeep Singh
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN
         1                   NaN            NaN            NaN

In [8]:
cd=data.groupby(['match_id','batsman'])['batsman_runs'].sum()

match_id  batsman
1         A Choudhary        6
          BCJ Cutting       16
          CH Gayle          32
          DA Warner         14
          DJ Hooda          16
          KM Jadhav         31
          MC Henriques      52
          Mandeep Singh     24
          S Aravind          0
          S Dhawan          40
          SR Watson         22
          STR Binny         11
          Sachin Baby        1
          TM Head           30
          TS Mills           6
          YS Chahal          3
          Yuvraj Singh      62
2         AM Rahane         60
          AT Rayudu         10
          BA Stokes         21
          HH Pandya         35
          JC Buttler        38
          KA Pollard        27
          KH Pandya          3
          MA Agarwal         6
          MS Dhoni          12
          N Rana            34
          PA Patel          19
          RG Sharma          3
          SPD Smith         84
                            ..
635       DJ Bravo          20
          DJ Hooda           4
          DR Smith           1
          DS Kulkarni        3
          ER Dwivedi         5
          KD Karthik        26
          MC Henriques      11
          NV Ojha           10
          RA Jadeja         19
          S Dhawan           0
          SK Raina           1
          Yuvraj Singh       8
636       AB de Villiers     5
          B Kumar            1
          BCJ Cutting       39
          Bipul Sharma       5
          CH Gayle          76
          CJ Jordan          3
          DA Warner         69
          DJ Hooda           3
          Iqbal Abdulla      4
          KL Rahul          11
          MC Henriques       4
          NV Ojha            7
          S Dhawan          28
          SR Watson         11
          STR Binny          9
          Sachin Baby       18
          V Kohli           54
          Yuvraj Singh      38
Name: batsman_runs, Length: 9515, dtype: int64

In [36]:
wick=data.groupby(['bowler'])['player_dismissed'].count()
wick

bowler
A Ashish Reddy        19
A Chandila            11
A Choudhary            5
A Flintoff             2
A Kumble              49
A Mishra             142
A Mithun               8
A Nehra              121
A Nel                  1
A Singh               31
A Symonds             23
A Uniyal               3
A Zampa               19
AA Chavan              8
AA Jhunjhunwala        1
AA Kazi                1
AA Noffke              1
AB Agarkar            33
AB Dinda              82
AB McDonald           14
AC Gilchrist           1
AC Thomas             16
AC Voges               1
AD Mascarenhas        19
AD Mathews            28
AD Russell            36
AF Milne               5
AG Murtaza            12
AJ Finch               1
AJ Tye                12
                    ...
TG Southee            25
TL Suman               7
TM Dilshan             5
TM Head                3
TP Sudhindra           1
TS Mills               5
Tejas Baroka           0
UT Yadav             107
Umar Gul              14
V Kohli                5
V Pratap Singh        12
V Sehwag               6
V Shankar              0
VR Aaron              40
VRV Singh             16
VS Malik               6
VS Yeligati            0
VY Mahesh             22
WA Mota                4
WD Parnell            31
WPUJC Vaas            22
Washington Sundar      9
Y Gnaneswara Rao       0
Y Nagar                4
Y Venugopal Rao        7
YA Abdulla            15
YK Pathan             45
YS Chahal             72
Yuvraj Singh          39
Z Khan               119
Name: player_dismissed, Length: 356, dtype: int64

In [9]:
cd0 = pd.DataFrame(cd)

In [34]:
ave_run=cd0.groupby('batsman')['batsman_runs'].mean().sort_values(ascending=False)
ave_run
ave_run.to_csv("avgrun.csv")

C:\Users\yash.chhabaria\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
yu=dict(ave_run)

In [12]:
yu['Yuvraj Singh']

22.336206896551722

In [13]:
#bowlers average economy 
bowl=data.groupby(['match_id','bowler','over'])['total_runs'].sum()
bowl_eco=pd.DataFrame(bowl)

bowl_eco

                                 total_runs
match_id bowler            over
1        A Choudhary       2             16
                           10             4
                           13            18
                           18            17
         A Nehra           1             11
                           3             16
                           11            13
                           18             2
         B Kumar           2              1
                           4             15
                           17             3
                           19             9
         BCJ Cutting       5              5
                           9             11
                           16            12
                           20             7
         Bipul Sharma      14             4
         DJ Hooda          7              7
         MC Henriques      10            13
                           12             7
         Rashid Khan       6              6
                           8             13
                           13             8
                           15             9
         S Aravind         5              9
                           12             8
                           15            19
         SR Watson         6             17
                           14             8
                           20            16
...                                     ...
636      BCJ Cutting       16             4
         Bipul Sharma      12             9
                           14             8
         CH Gayle          2              5
                           4              6
                           6             13
         CJ Jordan         10             9
                           12            13
                           17             9
                           19            16
         Iqbal Abdulla     8             10
         MC Henriques      7             10
                           9             21
                           15             9
         Mustafizur Rahman 6              4
                           10            12
                           17            10
                           19            12
         S Aravind         1              7
                           3              9
                           14             7
                           16             7
         SR Watson         5             19
                           11             6
                           18            12
                           20            24
         YS Chahal         7              6
                           9             13
                           13             4
                           15            13

[24405 rows x 1 columns]

In [24]:
#bowl_eco.reset_index(inplace=True)
tot_overs=bowl_eco.groupby('bowler')['over'].count()
tot_overs=pd.DataFrame(tot_overs)
tot_overs.reset_index(inplace=True)

In [25]:
tot_runs=bowl_eco.groupby('bowler')['total_runs'].sum()
tot_runs=pd.DataFrame(tot_runs)
#tot_runs.reset_index(inplace=True)
tot_runs

                   total_runs
bowler
A Ashish Reddy            400
A Chandila                245
A Choudhary               144
A Flintoff                106
A Kumble                 1089
A Mishra                 3305
A Mithun                  477
A Nehra                  2537
A Nel                      31
A Singh                   639
A Symonds                 694
A Uniyal                   67
A Zampa                   281
AA Chavan                 339
AA Jhunjhunwala           130
AA Kazi                    21
AA Noffke                  41
AB Agarkar               1174
AB Dinda                 2103
AB McDonald               263
AC Gilchrist                0
AC Thomas                 416
AC Voges                   76
AD Mascarenhas            365
AD Mathews               1095
AD Russell                917
AF Milne                  185
AG Murtaza                322
AJ Finch                   67
AJ Tye                    146
...                       ...
TG Southee                930
TL Suman                  198
TM Dilshan                368
TM Head                    81
TP Sudhindra              137
TS Mills                  157
Tejas Baroka               33
UT Yadav                 2802
Umar Gul                  198
V Kohli                   371
V Pratap Singh            300
V Sehwag                  236
V Shankar                  19
VR Aaron                 1250
VRV Singh                 549
VS Malik                  268
VS Yeligati                61
VY Mahesh                 511
WA Mota                    98
WD Parnell                731
WPUJC Vaas                364
Washington Sundar         189
Y Gnaneswara Rao            7
Y Nagar                   125
Y Venugopal Rao           338
YA Abdulla                311
YK Pathan                1421
YS Chahal                1600
Yuvraj Singh             1068
Z Khan                   2860

[356 rows x 1 columns]

In [32]:
total_bowl=pd.merge(tot_overs,tot_runs,on='bowler')
#total_bowl.sort_values()
a = total_bowl['total_runs']/total_bowl['over']
avg=pd.DataFrame(a,columns=['avg_economy'])
bowler_avg=pd.concat([total_bowl,avg],axis=1)

#bowler_avg.sort_values('total_runs',ascending=False)
bowler_avg_backup=bowler_avg
bowler_avg.sort_values('avg_economy')

                bowler  over  total_runs  avg_economy
20        AC Gilchrist     1           0     0.000000
209             N Rana     1           3     3.000000
310        Sachin Baby     2           8     4.000000
210           NB Singh     4          18     4.500000
32           AM Rahane     1           5     5.000000
301          SPD Smith     1           5     5.000000
205      Mohammad Nabi    11          59     5.363636
93         DJ Thornely     7          40     5.714286
274             S Rana     3          18     6.000000
45          Avesh Khan     4          24     6.000000
305          SS Mundhe     1           6     6.000000
179           M Manhas     7          42     6.000000
170      LA Carseldine     1           6     6.000000
1           A Chandila    39         245     6.282051
347  Washington Sundar    30         189     6.300000
141            JM Kemp     9          58     6.444444
300          SP Narine   323        2085     6.455108
109          GH Vihari     6          39     6.500000
192          MJ Clarke    11          72     6.545455
318      Sohail Tanvir    42         275     6.547619
130            J Yadav    30         197     6.566667
298    SMSM Senanayake    32         211     6.593750
146        JW Hastings    10          66     6.600000
234           R Ashwin   383        2552     6.663185
212      NJ Rimmington     3          20     6.666667
105         FH Edwards    24         160     6.666667
297         SM Pollock    46         307     6.673913
4             A Kumble   163        1089     6.680982
243          R Tewatia    21         141     6.714286
225     PD Collingwood    15         101     6.733333
..                 ...   ...         ...          ...
273           S Narwal    18         203    11.277778
173        LMP Simmons     3          34    11.333333
349            Y Nagar    11         125    11.363636
157          KJ Abbott    16         182    11.375000
151         K Santokie     8          91    11.375000
49            B Geeves     8          91    11.375000
280          SA Abbott     5          57    11.400000
330       TP Sudhindra    12         137    11.416667
61           BJ Rohrer     1          12    12.000000
176        LRPL Taylor     2          24    12.000000
247        RA Tripathi     1          12    12.000000
257            RR Bose     2          24    12.000000
195          MK Tiwary     6          73    12.166667
342        VS Yeligati     5          61    12.200000
77            CL White     7          86    12.285714
66         C Ganapathy     1          13    13.000000
193           MJ Henry     5          71    14.200000
40        Abdur Razzak     2          29    14.500000
202   Mashrafe Mortaza     4          59    14.750000
191           MG Neser     4          62    15.500000
319        Sunny Gupta     3          47    15.666667
104       F du Plessis     1          16    16.000000
75       CK Kapugedera     3          49    16.333333
277           S Sriram     3          49    16.333333
256         RR Bhatkal     2          35    17.500000
221         P Prasanth     1          18    18.000000
338          V Shankar     1          19    19.000000
48            B Chipli     1          20    20.000000
174          LPC Silva     1          21    21.000000
120         I Malhotra     1          23    23.000000

[356 rows x 4 columns]

In [27]:
dict_avgmk = bowler_avg.drop(['over','total_runs'],axis=1)

In [30]:
dict_avg=dict_avgmk.set_index('bowler')
dict_avg.loc['Harbajan ']

avg_economy    6.663185
Name: R Ashwin, dtype: float64

In [19]:
for i in bowl_eco.head():
    print (i)

total_runs

In [25]:
bowl_eco.to_csv('bowl_eco.csv',index=False)

In [26]:
be = bowl_eco.reset_index()

In [28]:
be.to_csv('bowl_ecos.csv',index=False)